# redis-ha:
#   enabled: true

controller:
  replicas: 1

server:
  replicas: 1
  service:
    type: LoadBalancer
  #extraArgs:
  #- --insecure

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1
  # replicaCount: 2

  